### PR TITLE
Debug collect - add processingUnitID to enforcer refresh

### PR DESCRIPTION
**Pull request by philipatl**

### CODE REVIEW

**Comment by philipatl** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "debug-collect-pcap",
    "component": "enforcerd",
    "pr-id": "1716",
    "commit-sha": "7a494bb18ce83111a390164f049e45a4d0115fe3",
    "pipeline": "master"
  },
  {
    "project": "debug-collect-pcap",
    "component": "gaia",
    "pr-id": "494",
    "commit-sha": "75ffb3f1003914ada50395db623813b1743639d2",
    "pipeline": "master"
  },
  {
    "project": "debug-collect-pcap",
    "component": "apoctl",
    "pr-id": "247",
    "commit-sha": "5f7ea192b53547cf102342d4d9254e9b844094b7",
    "pipeline": "master"
  },
  {
    "project": "debug-collect-pcap",
    "component": "backend",
    "pr-id": "734",
    "commit-sha": "952f3bd6d522ce227e1de49477370afa27814ee9",
    "pipeline": "master"
  }
]
```

**Comment by philipatl** [comment]
> The prop name is too generic. It did not understand what it was about without reading the doc

@primalmotion what about `debugPUID`? -- so much like `debugDuration` we know it's related to the EnforcerRefresh.Debug option

**Comment by primalmotion** [comment]
Yeah. I don't think we use PU a lot in the api. debugProcessingUnitID seems more inline

**Comment by philipatl** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "debug-collect-pcap",
    "component": "enforcerd",
    "pr-id": "1716",
    "commit-sha": "bbd25e8fc89d96efd4a9a8b2afa412d9ab5bf50e",
    "pipeline": "master"
  },
  {
    "project": "debug-collect-pcap",
    "component": "gaia",
    "pr-id": "494",
    "commit-sha": "137c3def1bbca41bfeb50dfebbb8b939bf0d15e2",
    "pipeline": "master"
  },
  {
    "project": "debug-collect-pcap",
    "component": "apoctl",
    "pr-id": "247",
    "commit-sha": "4b6ee5d37d21faf458014043d7027f9a53c1447d",
    "pipeline": "master"
  },
  {
    "project": "debug-collect-pcap",
    "component": "backend",
    "pr-id": "734",
    "commit-sha": "952f3bd6d522ce227e1de49477370afa27814ee9",
    "pipeline": "master"
  }
]
```

**Comment by philipatl** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "debug-collect-pcap",
    "component": "enforcerd",
    "pr-id": "1716",
    "commit-sha": "5c9ab245df52f5c765cbe4b07c387bd192e5b3d1",
    "pipeline": "master"
  },
  {
    "project": "debug-collect-pcap",
    "component": "gaia",
    "pr-id": "494",
    "commit-sha": "137c3def1bbca41bfeb50dfebbb8b939bf0d15e2",
    "pipeline": "master"
  },
  {
    "project": "debug-collect-pcap",
    "component": "apoctl",
    "pr-id": "247",
    "commit-sha": "4b6ee5d37d21faf458014043d7027f9a53c1447d",
    "pipeline": "master"
  },
  {
    "project": "debug-collect-pcap",
    "component": "backend",
    "pr-id": "734",
    "commit-sha": "952f3bd6d522ce227e1de49477370afa27814ee9",
    "pipeline": "master"
  }
]
```

**Pull request merged**
