### PR TITLE
fix: remove hs name validation

### PR DESCRIPTION
**Pull request by sibicramesh**
--> No longer needed with this PR https://github.com/aporeto-inc/enforcerd/pull/1303

### CODE REVIEW

**Comment by sibicramesh** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "host-service-name",
    "component": "enforcerd",
    "pr-id": "1303",
    "commit-sha": "33821d66e8ed1e3d385520fae8bf384d55769250"
  },
  {
    "project": "host-service-name",
    "component": "trireme-lib",
    "pr-id": "839",
    "commit-sha": "4bf2c6521228d0f7089fba3d0f77783f30fc2238"
  },
  {
    "project": "host-service-name",
    "component": "gaia",
    "pr-id": "371",
    "commit-sha": "c927dd3456a09355987c70346f6ce9a0f9aed212"
  }
]
```

**Comment by sibicramesh** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "host-service-name",
    "component": "enforcerd",
    "pr-id": "1303",
    "commit-sha": "cf9a2e3e33994b266ff44f850b8b7cbe611ef48f"
  },
  {
    "project": "host-service-name",
    "component": "trireme-lib",
    "pr-id": "839",
    "commit-sha": "4bf2c6521228d0f7089fba3d0f77783f30fc2238"
  },
  {
    "project": "host-service-name",
    "component": "gaia",
    "pr-id": "371",
    "commit-sha": "c927dd3456a09355987c70346f6ce9a0f9aed212"
  }
]
```

**Comment by dstiliadis** [comment]
We need a test with old enforcers and longer names. Also the regex should still be there (it should be valid characters), but just longer.

**Comment by sibicramesh** [comment]
> How old enforcers will react if they get a longer service name?

It won't start and you will see errors like these in the logs
```
ERROR	Error in processing event	{"error": "invalid pu id: adsadasdasdasdasdasdasdsadasdasdas1389721893782197392137821392179", "Event": {"eventtype":"start","putype":3,"puid":"adsadasdasdasdasdasdasdsadasdasdas1389721893782197392137821392179","name":"adsadasdasdasdasdasdasdsadasdasdas1389721893782197392137821392179.apomux-enforcerd-4","tags":["app:host:fqdn=apomux-enforcerd-4","app:host:name=adsadasdasdasdasdasdasdsadasdasdas1389721893782197392137821392179","app:host:id=5d2506285ed69729b398dc7d","app:host:namespace=/apomux"],"services":[{"ports":{"Min":22,"Max":22},"Port":0,"protocol":6}],"hostservice":true,"networktrafficonly":true}}
ERROR	Unable update profile with interface info	{"error": "Invalid request : Cannot handle request: invalid pu id: adsadasdasdasdasdasdasdsadasdasdas1389721893782197392137821392179\n"}
ERROR	Error in processing event	{"error": "invalid pu id: adsadasdasdasdasdasdasdsadasdasdas1389721893782197392137821392179", "Event": {"eventtype":"start","putype":3,"puid":"adsadasdasdasdasdasdasdsadasdasdas1389721893782197392137821392179","name":"adsadasdasdasdasdasdasdsadasdasdas1389721893782197392137821392179.apomux-enforcerd-4","tags":["app:host:fqdn=apomux-enforcerd-4","app:host:name=adsadasdasdasdasdasdasdsadasdasdas1389721893782197392137821392179","app:host:id=5d2506285ed69729b398dc7d","app:host:namespace=/apomux"],"services":[{"ports":{"Min":22,"Max":22},"Port":0,"protocol":6}],"hostservice":true,"networktrafficonly":true}}
ERROR	Unable update profile with interface info	{"error": "Invalid request : Cannot handle request: invalid pu id: adsadasdasdasdasdasdasdsadasdasdas1389721893782197392137821392179\n"}
```

**Comment by primalmotion** [comment]
well then it's not acceptable. changes must be backward compatible

**Pull request closed without merging**
