### PR TITLE
new: added additional info to graphedge

### PR DESCRIPTION
**Pull request by primalmotion**

### CODE REVIEW

**Comment by t00f** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "federation3",
    "component": "gaia",
    "pr-id": "480",
    "commit-sha": "8d1c34ea500192f5af6282f0d251693897fd3ce0",
    "pipeline": "master"
  },
  {
    "project": "federation3",
    "component": "backend",
    "pr-id": "733",
    "commit-sha": "471a53fc624fde5edb95bcd9ff60f1014ee4bcf8",
    "pipeline": "master"
  }
]
```

**Comment by t00f** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "federation3",
    "component": "gaia",
    "pr-id": "480",
    "commit-sha": "8d1c34ea500192f5af6282f0d251693897fd3ce0",
    "pipeline": "master"
  },
  {
    "project": "federation3",
    "component": "backend",
    "pr-id": "733",
    "commit-sha": "1b8e2f9ed1e2ef20a415d2089075de185ab6b63c",
    "pipeline": "master"
  }
]
```

**Comment by ericrpowers** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "federation3",
    "component": "gaia",
    "pr-id": "480",
    "commit-sha": "0413af44404c9a685f4d78557455b2863c9f0005",
    "pipeline": "master"
  },
  {
    "project": "federation3",
    "component": "backend",
    "pr-id": "733",
    "commit-sha": "44c7a0e9f8099c0d734842321f591f1ea9a22af8",
    "pipeline": "master"
  }
]
```

**Comment by primalmotion** [comment]
Random unrelated FT failure QA team is aware of. merging

**Pull request merged**
